version: '3.9'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=default-1
      - MYSQL_USER=sboot
      - MYSQL_PASSWORD=sboot123
    volumes:
      - mysql-volume:/var/lib/mysql
    command: --bind-address=0.0.0.0
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 1s
      retries: 10

volumes:
  mysql-volume:
    driver: local